### ISSUE TITLE
Segfault when installing Chromium beta

### ISSUE THREAD

**Issue by cassidyjames** [elementary/sideload#104]
## What Happened

I opened https://flathub.org/beta-repo/appstream/org.chromium.Chromium.flatpakref in Sideload and tried to install it. After confirming I wanted to install, the app closed. In Terminal, I see a segmentation fault.

## Expected Behavior

Chromium either installs or Sideload provides an intelligible error. 

## Steps to Reproduce

1. Download https://flathub.org/beta-repo/appstream/org.chromium.Chromium.flatpakref
2. Open the flatpakref
3. Confirm you want to install it

## Platform Information

elementary OS 6 daily build

**Comment by meisenzahl** [comment]
Can confirm

## Platform Information

elementary OS 6 daily build

**Comment by davidmhewitt** [comment]
This is a duplicate of #96 but #105 is marked to close both :)
