### ISSUE TITLE
Consider subclassing Granite.MessageDialog

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/sideload#111]
## Problem

Since `AbstractView` essentially looks like a `Granite.MessageDialog`, consider subclassing `Granite.MessageDialog` instead of a custom `AbstractView` so that design changes to `Granite.MessageDialog` is reflected in Sideload.

## Proposal

Subclass Granite.MessageDialog

**Comment by hanaral** [comment]
I'm not sure if MessageDialog is supposed to be used by itself; I think it was @jeremypw who said that to me a while back(?)

**Comment by danrabbit** [comment]
Since Sideload has a multi-page design, Granite.MessageDialog doesn't really work here
