### ISSUE TITLE
Use plugins

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/sideload#117]
## Problem

Currently, to install .deb or snaps, third party apps are required ([Eddy](https://github.com/donadigo/eddy) and [Snaptastic](https://github.com/bartzaalberg/snaptastic)). Although these apps are generally good, there is no guarantee that future changes to eOS's HIG/designs may make those third party apps feel out of place.

## Proposal

Similar to Wingpanel's indicators, File's plugins and Gala plugins, Sideload could use a plugin system where each plugin handles the install of filetypes. The plugin can then be separately installed by the user via the AppCenter which allows for the install of snaps, debs, AppImages (copy them to some directory and adding a .desktop), etc. while allowing AppCenter to handle natively supported installs from eOS's own repos.

## Prior Art

None. Just similar to what Sideload already is, perhaps with an additional badge/icon to show that it is a snap install, deb install, etc.

**Comment by cassidyjames** [comment]
Sideload is intended to be a super simple and straightforward Flatpak installer. I don't think we're interested in adding substantial complexity explicitly to support a use case we don't want to encourage. There's a reason we chose Flatpak, and other formats have other recommended methods of installation.
