### ISSUE TITLE
Installed apps don't show in Applications menu until restart. [Video]

### ISSUE THREAD

**Issue by elSolus** [elementary/sideload#128]
## What Happened

1. I installed LibreOffice, GIMP, Inkscape etc from flatpak (from ref files. Sideload its called, I guess?).
2. After install they don't show in the top-left menu (but yes, they show in the list as I type their name, so "searchable" and work as intended.).

Please check the video:

https://user-images.githubusercontent.com/77105020/129375647-4cb86143-9ef3-4a7a-9868-a5cfa2cb4ae0.mp4

3. I have to restart my PC to be able to see them there.
4. Is it a bug or that's the way it is supposed to be?

## Expected Behavior

Install an app and one should see this in the Applications Menu.

## Steps to Reproduce

1. Install an app from flatpak (ref file from flathub).
2. Open the Application menu.
3. It doesn't show there (but is searchable though)

## Platform Information

OS: elementary OS 6 Odin
CPU: Intel i5 3330
Mobo: Intel DH61WW
RAM: 6GB

**Comment by kdwk** [comment]
Can confirm this. Happening to me as well.

**Comment by davidmhewitt** [comment]
Thanks for the report!

This is an issue with the applications menu itself as it doesn't matter whether you install them via Sideload or via some other means. There's already an open issue for this here: https://github.com/elementary/applications-menu/issues/440

So I'll close this one as a duplicate.
