### ISSUE TITLE
Checkbox outline is cut off

### ISSUE THREAD

**Issue by lenemter** [elementary/sideload#144]
### What Happened?

Checkbox outline is cut off

![image](https://user-images.githubusercontent.com/80143868/180651894-f26388ff-bd1e-4284-88ee-0b8d66466ecd.png)

### Steps to Reproduce

1. Read readme.md or use Sideload

### Expected Behavior

Outline should not be cut off

Setting checkbox margin_bottom to 1 fixes this issue

### OS Version

6.x (Odin)

### Software Version

Compiled from git

**Comment by danrabbit** [comment]
Thanks for the report! This is due to a limitation of Gtk3. It should be fixed in #138 without having to add extra margins
