### ISSUE TITLE
Handke flatpak+https scheme

### ISSUE THREAD

**Issue by tintou** [elementary/sideload#169]
Other appstores will be implementing support for this
flatpak+https://dl.flathub.org/repo/appstream/re.sonny.Workbench.flatpakref 

(See https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/2089 for GNOME Software implementation)

**Comment by razzeee** [comment]
KDE implementation here https://invent.kde.org/plasma/discover/-/merge_requests/750
