### ISSUE TITLE
Use more generic copy if AppCenter is not installed

### ISSUE THREAD

**Issue by danrabbit** [elementary/sideload#46]
Before declaring that updates and removals can be handled by AppCenter, we should check that AppCenter is installed.

If it's not, we probably need some more generic copy

**Comment by cassidyjames** [comment]
We might want to hook off of DE being Pantheon _and_ AppCenter being installed so we don't end up with tons of different states, since we make assumptions about both.

Pantheon + AppCenter:

>Open it any time from the Applications Menu. Visit AppCenter for app information, updates, and to uninstall.

Other:

>Open it any time from your regular app launcher. App information, updates, and uninstallation may be handled by your software center.

…thoughts?

**Comment by danrabbit** [comment]
Yeah that seems like adequate copy to me :)
