### ISSUE TITLE
“Open App” hangs when Flatpak CLI is not installed

### ISSUE THREAD

**Issue by cassidyjames** [elementary/sideload#64]
~If an app is already installed~ _If you don't have the `flatpak` cli installed_ and you open its .flatpakref with Sideload, then hit the “Open App” button, Sideload hangs.

**Comment by davidmhewitt** [comment]
Can you reproduce this on the branch associated with #63 ? Or can you link the .flatpakref you're having issues with in case it's specific to that? I'm not able to reproduce that here.

**Comment by cassidyjames** [comment]
@davidmhewitt so I think this was actually caused by https://github.com/elementary/os/issues/234 as I can't reproduce it after installing Flatpak itself.
