### ISSUE TITLE
Matching GTK stylesheet not installed

### ISSUE THREAD

**Issue by cassidyjames** [elementary/sideload#67]
The Flatpak CLI installs a matching GTK stylesheet when you install an app. It looks like Sideload does not do that; so if you've never installed a Flatpak via CLI and install one with Sideload (the expected case for elementary OS in the future), you end up with Adwaita-styled apps.

**Comment by danrabbit** [comment]
Is it a bug or a feature? Maybe it’s better for apps installed with Sideload to use Adwaita?

**Comment by cassidyjames** [comment]
@danrabbit it's actually an invalid issue. I had installed Epiphany with Sideload and it uses Adwaita, but that's because the remote doesn't contain the elementary stylesheet, it couldn't auto-install it. Installing any app from Flathub correctly installs the stylesheet.

Apps should use whatever stylesheet they define. If they don't define any, the default behavior for Flatpak is to try to use the same name as the system one, and Flatpak automatically installs the smae stylesheet as the system one if it exists on the remote; to change that behavior, we'd need to change Flatpak itself (not Sideload).
