### ISSUE TITLE
Use "Sideload" instead of "Install"?

### ISSUE THREAD

**Issue by cassidyjames** [elementary/sideload#73]
I just realized we never use the word "Sideload" in the app UI, and it's only visible as the tooltip on the dockitem. I wonder if we should use the term more in the UI itself to make it a more familiar term, since we otherwise consistently use the term "sideload" for installing apps from outside of AppCenter?

**Comment by cassidyjames** [comment]
We could also make the title a little less scary by just saying, “Sideload app?” The implications below would remain the same, but it might come off a little better.

**Comment by fabiozaramella** [comment]
I don't know, "Install" is more generic to the user than "Sideload" and the latter is also more difficult to properly translate in other languages where you would end up with a much more verbose sentence explaining the actual meaning/action implied.
