### ISSUE TITLE
"Other apps from this distributor may appear in AppCenter"

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/sideload#83]
I use 100% Free Software. However, if I install only one Free Software app via Flathub, all proprietary apps of this platform will also be displayed in AppCenter. However, most app developers offer their Free Software Flatpak apps only on Flathub and do not distribute it additionally via their own direct channels, which are then free of proprietary software, for reasons of scarce resources.

There is already an idea, but it hasn't offered a solution for over a year now. flathub/flathub#691

So I ask myself, how can Sideload & AppCenter support me in the meantime in this ethical dilemma?

**Comment by TingPing** [comment]
Sideload could just ask to add the remote or not.

**Comment by danrabbit** [comment]
I'm going to close this as "Out of Scope" for sideload. It's not within the scope of this code base or the AppCenter code base to curate 3rd party repositories in any way. If you want to see only Open Source software in AppCenter, you can stick to the AppCenter repository and remotes that disallow closed source software.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for your feedback and the hint for a possible handling of my ethical dilemma! So this is how I will do it.

**Comment by 4jNsY6fCVqZv** [comment]
News from today: "Fedora discusses advertising for proprietary software in Gnome Software".

https://pagure.io/fedora-workstation/issue/111

https://meetbot.fedoraproject.org/fedora-meeting-2/2019-11-25/workstation.2019-11-25-14.00.html

How do you feel about it?

**Comment by cassidyjames** [comment]
We don't show banners for anything but curated AppCenter apps, which are entirely open source. Out of the box, elementary OS does not come with proprietary remotes added.

**Comment by 4jNsY6fCVqZv** [comment]
And how do you estimate the use case that users are going to use Flathub because otherwise it is sometimes quite difficult to stay with the app versions of a Ubuntu LTS - e.g. bugs for the Evince version in elementary are no longer fixed because the resources are too scarce and the version is too old for the maintainers, but this means that I cannot fill and edit business PDFs with it.
About Flathub: That's also an in-between thing. It's not really a proprietary remote, but one that keeps such content available and then makes it visible in AppCenter, is it?
Are you planning your own solution for elementary OS curated Flatpaks?

**Comment by 4jNsY6fCVqZv** [comment]
p.s. Can I currently remove remotes from my system easily and without leftovers, if I have previously integrated them via Sideload? Example also here Flathub.
