### ISSUE TITLE
Flatpak Support not working out of the box on 5.1

### ISSUE THREAD

**Issue by anarchyreloaded** [elementary/sideload#85]
I have updated my installation of elementary os to 5.1 yesterday and I'm sad to say that installing flatpaks from flathub out of vivaldi (my preferred browser) just doesn't work. It downloads a file, but if I try to open that my texteditor opens. I try to look for an app called sideload but it just doesn't seem to be there...

**Comment by cassidyjames** [comment]
I'm not sure what UI Vivaldi uses to show what apps to open with (or if you were doing that in Files), but Sideload should definitely be installed. You can confirm by typing `io.elementary.sideload` into the search in the Applications Menu and seeing if Sideload appears there.

**Comment by rythmkraze** [comment]
Installed gnome builder using sideload, but I cannot find the installed app.
`io.elementary.sideload` `https://flathub.org/repo/appstream/org.gnome.Builder.flatpakref`

`flatpak list` also does not list the Builder app either.

**Comment by cassidyjames** [comment]
It sounds like these may have been one-off issues that we're unable to reproduce. If you find a way to reliably reproduce it on a fresh install of elementary OS, let us know and we can re-open.
