### ISSUE TITLE
Flatpak apps are not using elementary theme

### ISSUE THREAD

**Issue by Yzelast** [elementary/sideload#86]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Flatpak apps installed from flathub are not using the elementary theme.

### Screenshots or screen recordings
![Captura de tela de 2019-12-08 04-20-48](https://user-images.githubusercontent.com/8459626/70386689-23741e00-1972-11ea-9999-1d005186b851.png)

## Platform Information
![Captura de tela de 2019-12-08 04-17-10](https://user-images.githubusercontent.com/8459626/70386657-cd9f7600-1971-11ea-9f24-566b3f0c4280.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by alatiera** [comment]
Hi, could you provide some examples of which apps you tried? In the screenshot you provided of Netbeans it looks like its using the theme (maybe a slightly older version?).

This behavior will vary between apps, and ultimately comes down to what each app developers decides to do with the application :)

**Comment by Yzelast** [comment]
After installing some other stuff it looks that app themes are somewhat random...

Geany(native):
![Captura de tela de 2019-12-08 18-07-15](https://user-images.githubusercontent.com/8459626/70397109-ad110380-19e5-11ea-9128-3f9c5d2ed8ed.png)

Geany(snap): does not open

Geany(flatpak):
![Captura de tela de 2019-12-08 18-11-13](https://user-images.githubusercontent.com/8459626/70397159-34f70d80-19e6-11ea-88dd-5070006d6dc7.png)

arduinoIDE(snap):
![Captura de tela de 2019-12-08 17-48-05](https://user-images.githubusercontent.com/8459626/70397115-cd40c280-19e5-11ea-8b9a-e0a20b9e73a0.png)

arduinoIDE(flatpak):
![Captura de tela de 2019-12-08 17-48-29](https://user-images.githubusercontent.com/8459626/70397118-d9c51b00-19e5-11ea-9f1d-dc1143c4f247.png)


netbeans(snap):
![Captura de tela de 2019-12-08 17-35-05](https://user-images.githubusercontent.com/8459626/70397127-eb0e2780-19e5-11ea-8633-6ec63dc5a2a5.png)

netbeans(flatpak):
![Captura de tela de 2019-12-08 16-53-38](https://user-images.githubusercontent.com/8459626/70397132-f6615300-19e5-11ea-9aa4-4f91e423c477.png)

Well, i was hoping that with flatpak support it would be easier to install and get apps from a single source...looks like i will have to continue using debs+ppas+snaps+flatpaks if i want to have a consistent theme within my apps.

**Comment by Exalm** [comment]
The missing Geary icon is a bug, but otherwise all 3 apps in flatpak are using elementary theme. In any case, none of them are elementary apps, your can't really expect them to look any consistent.

**Comment by cassidyjames** [comment]
To further add to @Exalm's point, most of those apps don't even appear to be using GTK3. Packaging technology has nothing to do with how native or not those apps look.
