### ISSUE TITLE
Trash .flatpakref on success

### ISSUE THREAD

**Issue by cassidyjames** [elementary/sideload#91]
There's not a big reason to keep the .flatpakref file around on disk once we're done, so it might be worth having a checkbox to trash it.

**Comment by 4jNsY6fCVqZv** [comment]
I wonder whether this could be a useful extension of Housekeeping.

**Comment by Oymate** [comment]
Firefox deletes these later anyway

**Comment by cassidyjames** [comment]
@Oymate _if_ you're using Firefox, _and_ depending on how you downloaded them. If you open them directly, sure, Firefox opens them from a temporary directory. But we don't ship Firefox, and this is still useful if you download them and open them later.

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv eh, I don't really think so. This is a one-time thing that can be handled inside Sideload on success; we don't want/need to constantly clean them up on a schedule, which is what Housekeeping handles.
